# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

matrix:
  include:
    - osx_image: xcode9
      env: DESTINATION="iPhone X (11.0)" SWIFT_VERSION="4.0"

language: objective-c
before_install:
# Grepping destination device udid
- DESTINATION_UDID=$(instruments -s devices | grep "$DESTINATION \[" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g')
# Prelaunching simulator to avoid timeout https://github.com/travis-ci/travis-ci/issues/6422
- open -a "simulator" --args -CurrentDeviceUDID $DESTINATION_UDID
script:
- set -o pipefail && xcodebuild test
 `` -enableCodeCoverage YES
 `` -project JobQueueExample/JobQueueExample.xcodeproj
 `` -scheme JobQueueExample
 `` -sdk iphonesimulator
 `` -destination "id=$DESTINATION_UDID"
 `` ONLY_ACTIVE_ARCH=NO
 `` | xcpretty
